name: Documentation

on:
  push:
    branches:
      - main # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:

jobs:
  texbuild:
    permissions:
      actions: write
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/latex
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Install pdflatex, imagemagick
        run: sudo apt-get install texlive-latex-base imagemagick texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
      - name: Build LaTex
        run: ./make.sh
  build:
    needs: texbuild
    permissions:
      actions: write
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v1
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7.2'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
          GKSwstype: "100" # https://discourse.julialang.org/t/generation-of-documentation-fails-qt-qpa-xcb-could-not-connect-to-display/60988
        run: julia --project=docs/ docs/make.jl
